Q1)WriteaPHPscriptforthefollowing:Designaformtoacceptastring.Writeafunctiontocountthetotalnumberofvowels(a,e,i,o,u) fromthestring.Showtheoccurrencesofeachvowelfromthestring.Checkwhetherthegivenstringisapalindromeornot,withoutusingbuilt-infunction.(Useradiobuttonsandtheconceptoffunction.Use‘include’constructorrequirestmt.)


Ans:
slip1.html(filenamesvaeasXammp->htdocsfloder)Eg.C:\xampp\htdocs\ravi)
<html>
<body>
<formaction="slip.php"method="post"><h3>EnterSting:<inputtype="text"name="str"maxlength="20"></h3>
<h4>Opertions:</h4>
<inputtype="radio"name="op"value="1">TotalVowels<br><inputtype="radio"name="op"value="2">Occurances<br><br><inputtype="radio"name="op"value="3">CheckStringisPalindromorNot<br><br>
<inputtype="submit"value="show"></form>
</body>
</html>
Slip.php
<?php
functioncnt_vowels($a,$l){
$v_cnt=0;
for($i=0;$i<$l;$i++){
if(($a[$i]=='a')||($a[$i]=='e')||($a[$i]=='i')||($a[$i]=='o')||($a[$i]=='u')||($a[$i]=='A')||($a[$i]=='E')||($a[$i]=='I')||($a[$i]=='O')||($a[$i]=='U'))$v_cnt++;}
return$v_cnt;}
functionoccur_vowels($a,$l){
$av=$ev=$iv=$ov=$uv=$cnt=0;for($i=0;$i<$l;$i++){
if(($a[$i]=='a')||($a[$i]=='A'))$av++;elseif(($a[$i]=='e')||($a[$i]=='E'))$ev++;elseif(($a[$i]=='i')||($a[$i]=='I'))
$iv++;elseif(($a[$i]=='o')||($a[$i]=='O'))$ov++;
elseif(($a[$i]=='u')||
($a[$i]=='U'))
$uv++;
else$cnt++;
}
echo"<br>Total'a':$av";echo"<br>Total'e':$ev";echo"<br>Total'i':$iv";echo"<br>Total'o':$ov";echo"<br>Total'u':$uv";echo"<br>Totalconsenentsare:$cnt";$tot=$av+$ev+$iv+$ov+$uv;return$tot;
}
$str=$_POST['str'];
$op=$_POST['op'];
$l=strlen($str);
switch($op)
{
case1:echo"stringis::$str<br>";$v_cnt=cnt_vowels($str,$l);echo"Totalvowelsare::$v_cnt<br>";
break;case2:echo"stringis::$str<br>";$v_occ=occur_vowels($str,$l);echo"lenghtis::$v_occ<br>";break;}
$str1=strrev($str);
$a=strlen($str);
$f=0;
for($j=0;$j<$a;$j++)
{
if($str1[$j]==$str[$j])
{
$f=0;
}
else
{
$f=1;
break;
}
}
if($f==0)
{
echo"stringispalindrome";
}
else
{
echo"stringisnotpalindrome";}
?>



////////////////////////////////////////////////////////////////////////////////////////////////////

Q.2WriteaPHPscriptforthefollowing:Designaformtoaccepttwostringsfromtheuser.Findthefirstoccurrenceandthelastoccurrenceofthesmallstringinthelargestring.Alsocountthetotalnumberofoccurrencesofsmallstringinthelargestring.Provideatextboxtoacceptastring,whichwillreplacethesmallstringinthelargestring.(Usebuilt-infunctions)
Ans:-
slip2.html
<html>
<body>
<formaction="rslip2.php"method="get"><center>
<table>
<tr><td>Enter1stString:</td><td><inputtype="text"name="str1"></td><tr>
<tr><td>Enter2ndString:</td><td><inputtype="text"name="str2"></td></tr>
<tr><td>EnterStringToReplace:</td><td><inputtype="text"name="str3"></td></tr>
<tr><td>Occurance</td><td><inputtype="radio"name="ch"value=1></td></tr>
<tr><td>Replace</td><td><inputtype="radio"name="ch"value=2></td></tr>
<tr><td></td><td><inputtype="submit"value=Next></td></tr></table>
</center>
</form>
</body>
</html>
rslip.php
<?php
$str1=$_GET['str1'];
$str2=$_GET['str2'];
$str3=$_GET['str3'];
$ch=$_GET['ch'];
echo"FirstStringis=$str1.<br><br>";echo"secondStringis=".$str2."<br><br>";echo"StringforReplaceis=".$str3."<br><br>";If(strlen($str1)>strlen($str2))
{
switch($ch){
case1:$pos=strpos($str1,$str2);if($pos!=0)echo"string'$str2'Notpresentatthestartof'$str1'.<br>";
elseecho"string'$str2'presentatthestartof'$str1'.<br>";
break;case2:$str4=str_replace($str2,$str3,$str1);echo"Afterreplacingstring$str4";break;}
}
else
{
switch($ch){
case1:$pos=strpos($str2,$str1);if($pos!=0)echo"string'$str1'Notpresentatthestartof'$str2'.<br>";
elseecho"string'$str1'presentatthestartof'$str2'.<br>";
break;case2:$str4=str_replace($str1,$str3,$str2);echo"Afterreplacingstring$str4";break;}
}
?>


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


Q.3:-WriteaPHPscriptforthefollowing:Designaformtoaccepttwonumbersfromtheuser.Giveoptionstochoosethearithmeticoperation(useradiobuttons).Displaytheresultonthenextform.(Usetheconceptoffunctionanddefaultparameters.Use‘include’constructorrequirestmt).Ans:-
slip3.html
<html>
<body>
<FORMACTION="rslip3.php"method="GET"><table>
<tr><td><h3>Enterfirstno:</td><td><inputtype=textname=no1></h3></td></tr>
<tr><td><h3>Entersecondno:</td><td><inputtype=textname=no2></h3></td></tr>
<tr><td><b>SelectOperationwhichuhavetoperform:</b></td></tr>
<tr><td><inputtype=radiovalue="1"name=cal>Addition</td></tr>
<tr><td><inputtype=radiovalue="2"name=cal>Substraction</td></tr><tr><td><inputtype=radiovalue="3"name=cal>Multiplication</td></tr><tr><td><inputtype=radiovalue="4"name=cal>Division</td></tr>
<tr><td></td><td><inputtype=submitname=submitvalue=Calculate></td></tr>
</table>
</form>
</body>
</html>
rslip.php
<?php
$no1=$_GET['no1'];$no2=$_GET['no2'];$cal=$_GET['cal'];
if($cal==1)
{
$add=$no1+$no2;
echo"<h1>addition=".$add."</h1>";}
elseif($cal==2)
{
$sub=$no1-$no2;
echo"<h1>subtraction=".$sub."</h1>";}
elseif($cal==3)
{
$mult=$no1*$no2;
echo"<h1>multiplication=".$mult."</h1>";
}
elseif($cal==4)
{
$div=$no1/$no2;
echo"<h1>division=".$div."</h1>";}
?>